### ISSUE TITLE
Module still uses deprected/removed TEMPLATE_DEBUG settings var

### ISSUE THREAD

**Issue by ashb** [jaylett/django-render-as#3]
Specifically TEMPLATE_DEBUG is still being looked for, and if you make a syntax error in the template I get `AttributeError: 'Settings' object has no attribute 'TEMPLATE_DEBUG'` masking the original cause of the error.

**Comment by jaylett** [comment]
This should be fixed in 725faebc197f0d776229149fd1cd387e7d56dd96 and v1.2 (on pypi).
